//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int id { get; set; }
        public int idDocumentType { get; set; }
        public string documentNumber { get; set; }
        public System.DateTime birthdate { get; set; }
        public int idCity { get; set; }
        public string movilNumber { get; set; }
        public string name { get; set; }
    
        public virtual City City { get; set; }
        public virtual DocumentsType DocumentsType { get; set; }
    }
}
