//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public class Customer
    {
        [DataMember]
        public int id { get; set; }

        [DataMember]
        public int idDocumentType { get; set; }

        [DataMember]
        public string documentNumber { get; set; }

        [DataMember]
        public System.DateTime birthdate { get; set; }

        [DataMember]
        public int idCity { get; set; }

        [DataMember]
        public string movilNumber { get; set; }

        [DataMember]
        public string name { get; set; }

        [DataMember]
        public virtual City City { get; set; }
        public virtual DocumentsType DocumentsType { get; set; }
    }
}
